# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.5
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: ubohodickson@gmail.com
author_name: UbGreat
contract_name: dikihealth
preset_name: production
project_name: dikihealth-algorand

